[book]
authors = ["Celestia Labs"]
language = "en"
multilingual = false
src = "src"
title = "Celestia Specifications"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/celestiaorg/celestia-specs"

[rust]
edition = "2018"
