[book]
authors = ["LazyLedger Labs"]
language = "en"
multilingual = false
src = "src"
title = "LazyLedger Specifications"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/lazyledger/lazyledger-specs"

[rust]
edition = "2018"
